// packages/uni-components/src/vue/slider/index.tsx
import { computed, inject, onMounted, onBeforeUnmount, ref, watch } from 'vue'
import type { ExtractPropTypes, Ref } from 'vue'
import { defineBuiltInComponent } from '../../helpers/component'
import { useTouchtrack, TouchtrackEvent } from '../../helpers/useTouchtrack'
import {
  CustomEventTrigger,
  useCustomEvent,
  EmitEvent,
  withWebEvent,
} from '../../helpers/useEvent'
import { UniFormCtx, uniFormKey } from '../form'

const props = {
  name: {
    type: String,
    default: '',
  },
  min: {
    type: [Number, String],
    default: 0,
  },
  max: {
    type: [Number, String],
    default: 100,
  },
  value: {
    type: [Number, String],
    default: 0,
  },
  step: {
    type: [Number, String],
    default: 1,
  },
  disabled: {
    type: [Boolean, String],
    default: false,
  },
  color: {
    type: String,
    default: '#e9e9e9',
  },
  backgroundColor: {
    type: String,
    default: '#e9e9e9',
  },
  activeColor: {
    type: String,
    default: '#007aff',
  },
  selectedColor: {
    type: String,
    default: '#007aff',
  },
  blockColor: {
    type: String,
    default: '#ffffff',
  },
  blockSize: {
    type: [Number, String],
    default: 28,
  },
  showValue: {
    type: [Boolean, String],
    default: false,
  },
}

type SliderProps = ExtractPropTypes<typeof props>
type HTMLRef = Ref<HTMLElement | null>

class UniSliderElement extends HTMLElement {
  get value() {
    return Number(this.getAttribute('value'))
  }

  set value(value: number) {
    this.dispatchEvent(new CustomEvent('change', { detail: { value } }))
  }
}

export default /*#__PURE__*/ defineBuiltInComponent({
  name: 'Slider',
  props,
  emits: ['changing', 'change'],
  //#if _X_ && !_NODE_JS_ /* 仅限X项目以及非SSR环境，使用条件编译，可以尽量减少其他平台生成多余的代码 */
  rootElement: {
    name: 'uni-slider',
    class: UniSliderElement,
  },
  //#endif
  setup(props, { emit }) {
    const sliderRef: HTMLRef = ref(null)
    const sliderValueRef: HTMLRef = ref(null)
    const sliderHandleRef: HTMLRef = ref(null)
    const sliderValue = ref(Number(props.value))
    watch(
      () => props.value,
      (val) => {
        sliderValue.value = Number(val)
      }
    )

    const trigger = useCustomEvent<EmitEvent<typeof emit>>(sliderRef, emit)

    const state = useSliderState(props, sliderValue)
    const { _onClick, _onTrack } = useSliderLoader(
      props,
      sliderValue,
      sliderRef,
      sliderValueRef,
      trigger
    )

    onMounted(() => {
      useTouchtrack(sliderHandleRef.value!, _onTrack)
    })

    function onUniSliderChange(e: CustomEvent) {
      sliderValue.value = Number(e.detail.value)
    }

    return () => {
      const { setBgColor, setBlockBg, setActiveColor, setBlockStyle } = state

      return (
        <uni-slider
          ref={sliderRef}
          onClick={withWebEvent(_onClick)}
          //#if _X_ && !_NODE_JS_
          value={sliderValue.value}
          onChange={withWebEvent(onUniSliderChange)}
          //#endif
        >
          <div class="uni-slider-wrapper">
            <div class="uni-slider-tap-area">
              <div style={setBgColor.value} class="uni-slider-handle-wrapper">
                <div
                  ref={sliderHandleRef}
                  style={setBlockBg.value}
                  class="uni-slider-handle"
                />
                <div style={setBlockStyle.value} class="uni-slider-thumb" />
                <div style={setActiveColor.value} class="uni-slider-track" />
              </div>
            </div>
            <span
              v-show={props.showValue}
              ref={sliderValueRef}
              class="uni-slider-value"
            >
              {sliderValue.value}
            </span>
          </div>
          <slot />
        </uni-slider>
      )
    }
  },
})

function useSliderState(props: SliderProps, sliderValue: Ref<number>) {
  const _getValueWidth = () => {
    const max = Number(props.max)
    const min = Number(props.min)
    return (100 * (sliderValue.value - min)) / (max - min) + '%'
  }
  const _getBgColor = () => {
    return props.backgroundColor !== '#e9e9e9'
      ? props.backgroundColor
      : props.color !== '#007aff'
      ? props.color
      : '#007aff'
  }
  const _getActiveColor = () => {
    return props.activeColor !== '#007aff'
      ? props.activeColor
      : props.selectedColor !== '#e9e9e9'
      ? props.selectedColor
      : '#e9e9e9'
  }

  const state = {
    setBgColor: computed(() => ({ backgroundColor: _getBgColor() })),
    setBlockBg: computed(() => ({ left: _getValueWidth() })),
    setActiveColor: computed(() => ({
      backgroundColor: _getActiveColor(),
      width: _getValueWidth(),
    })),
    setBlockStyle: computed(() => ({
      width: props.blockSize + 'px',
      height: props.blockSize + 'px',
      marginLeft: -props.blockSize / 2 + 'px',
      marginTop: -props.blockSize / 2 + 'px',
      left: _getValueWidth(),
      backgroundColor: props.blockColor,
    })),
  }

  return state
}

function useSliderLoader(
  props: SliderProps,
  sliderValue: Ref<number>,
  sliderRef: HTMLRef,
  sliderValueRef: HTMLRef,
  trigger: CustomEventTrigger
) {
  const _onClick = ($event: MouseEvent) => {
    if (props.disabled) {
      return
    }
    _onUserChangedValue($event)
    trigger('change', $event, {
      value: sliderValue.value,
    })
  }

  const _filterValue = (e: number) => {
    const max = Number(props.max)
    const min = Number(props.min)
    const step = Number(props.step)
    return e < min
      ? min
      : e > max
      ? max
      : computeController.mul.call(Math.round((e - min) / step), step) + min
  }

  const _onUserChangedValue = (e: MouseEvent) => {
    const max = Number(props.max)
    const min = Number(props.min)
    const sliderRightBox = sliderValueRef.value!
    const sliderRightBoxLeft = getComputedStyle(sliderRightBox, null).marginLeft
    let sliderRightBoxWidth = sliderRightBox.offsetWidth
    sliderRightBoxWidth = sliderRightBoxWidth + parseInt(sliderRightBoxLeft)
    const slider = sliderRef.value!
    const offsetWidth =
      slider.offsetWidth - (props.showValue ? sliderRightBoxWidth : 0)
    const boxLeft = slider.getBoundingClientRect().left
    const value = ((e.x - boxLeft) * (max - min)) / offsetWidth + min
    sliderValue.value = _filterValue(value)
  }

  const _onTrack = (e: TouchtrackEvent) => {
    if (!props.disabled) {
      return e.detail.state === 'move'
        ? (_onUserChangedValue({
            x: e.detail.x,
          } as MouseEvent),
          trigger('changing', e as any, {
            value: sliderValue.value,
          }),
          !1)
        : e.detail.state === 'end' &&
            trigger('change', e as any, {
              value: sliderValue.value,
            })
    }
  }

  const uniForm = inject<UniFormCtx>(uniFormKey, false as unknown as UniFormCtx)
  if (!!uniForm) {
    const field = {
      reset: () => (sliderValue.value = Number(props.min)),
      submit: () => {
        const data: [string, any] = ['', null]
        if (props.name !== '') {
          data[0] = props.name
          data[1] = sliderValue.value
        }
        return data
      },
    }
    uniForm.addField(field)
    onBeforeUnmount(() => {
      uniForm.removeField(field)
    })
  }

  return { _onClick, _onTrack }
}

var computeController = {
  mul: function (arg: number) {
    let m = 0
    let s1 = this.toString()
    let s2 = arg.toString()
    try {
      // 获得小数位数
      m += s1.split('.')[1].length
    } catch (e) {}
    try {
      // 获得小数位数
      m += s2.split('.')[1].length
    } catch (e) {}
    // 转为十进制计算后，要除以两个数的共同小数位数
    return (
      (Number(s1.replace('.', '')) * Number(s2.replace('.', ''))) /
      Math.pow(10, m)
    )
  },
}

// packages/uni-components/src/components/slider/index.vue
<template>
  <uni-slider
    ref="uni-slider"
    v-bind="$attrs"
    @click="_onClick"
  >
    <div class="uni-slider-wrapper">
      <div class="uni-slider-tap-area">
        <div
          :style="setBgColor"
          class="uni-slider-handle-wrapper"
        >
          <div
            ref="uni-slider-handle"
            :style="setBlockBg"
            class="uni-slider-handle"
          />
          <div
            :style="setBlockStyle"
            class="uni-slider-thumb"
          />
          <div
            :style="setActiveColor"
            class="uni-slider-track"
          />
        </div>
      </div>
      <span
        v-show="showValue"
        class="uni-slider-value"
      >{{ sliderValue }}</span>
    </div>
    <slot />
  </uni-slider>
</template>
<script>
import {
  emitter,
  listeners
} from '../../mixins'
import touchtrack from '../../mixins/touchtrack'
export default {
  name: 'Slider',
  mixins: [emitter, listeners, touchtrack],
  props: {
    name: {
      type: String,
      default: ''
    },
    min: {
      type: [Number, String],
      default: 0
    },
    max: {
      type: [Number, String],
      default: 100
    },
    value: {
      type: [Number, String],
      default: 0
    },
    step: {
      type: [Number, String],
      default: 1
    },
    disabled: {
      type: [Boolean, String],
      default: false
    },
    color: {
      type: String,
      default: '#e9e9e9'
    },
    backgroundColor: {
      type: String,
      default: '#e9e9e9'
    },
    activeColor: {
      type: String,
      default: '#007aff'
    },
    selectedColor: {
      type: String,
      default: '#007aff'
    },
    blockColor: {
      type: String,
      default: '#ffffff'
    },
    blockSize: {
      type: [Number, String],
      default: 28
    },
    showValue: {
      type: [Boolean, String],
      default: false
    }
  },
  data () {
    return {
      sliderValue: Number(this.value)
    }
  },
  computed: {
    setBlockStyle () {
      return {
        width: this.blockSize + 'px',
        height: this.blockSize + 'px',
        marginLeft: -this.blockSize / 2 + 'px',
        marginTop: -this.blockSize / 2 + 'px',
        left: this._getValueWidth(),
        backgroundColor: this.blockColor
      }
    },
    setBgColor () {
      return {
        backgroundColor: this._getBgColor()
      }
    },
    setBlockBg () {
      return {
        left: this._getValueWidth()
      }
    },
    setActiveColor () { // 有问题，设置最大值最小值是有问题
      return {
        backgroundColor: this._getActiveColor(),
        width: this._getValueWidth()
      }
    }
  },
  watch: {
    value (val) {
      this.sliderValue = Number(val)
    }
  },
  mounted () {
    this.touchtrack(this.$refs['uni-slider-handle'], '_onTrack')
  },
  created () {
    this.$dispatch('Form', 'uni-form-group-update', {
      type: 'add',
      vm: this
    })
  },
  beforeDestroy () {
    this.$dispatch('Form', 'uni-form-group-update', {
      type: 'remove',
      vm: this
    })
  },
  methods: {
    _onUserChangedValue (e) {
      const slider = this.$refs['uni-slider']
      const offsetWidth = slider.offsetWidth
      const boxLeft = slider.getBoundingClientRect().left
      const value = (e.x - boxLeft) * (this.max - this.min) / offsetWidth + Number(this.min)
      this.sliderValue = this._filterValue(value)
    },
    _filterValue (e) {
      return e < this.min ? this.min : e > this.max ? this.max : Math.round((e - this.min) / this
        .step) * this.step + Number(this.min)
    },
    _getValueWidth () {
      return 100 * (this.sliderValue - this.min) / (this.max - this.min) + '%'
    },
    _getBgColor () {
      return this.backgroundColor !== '#e9e9e9' ? this.backgroundColor : (this.color !== '#007aff' ? this.color
        : '#007aff')
    },
    _getActiveColor () {
      return this.activeColor !== '#007aff' ? this.activeColor : (this.selectedColor !== '#e9e9e9' ? this.selectedColor
        : '#e9e9e9')
    },
    _onTrack: function (e) {
      if (!this.disabled) {
        return e.detail.state === 'move' ? (this._onUserChangedValue({
          x: e.detail.x0
        }), this.$trigger('changing', e, {
          value: this.sliderValue
        }), !1) : (e.detail.state === 'end' && this.$trigger('change', e, {
          value: this.sliderValue
        }))
      }
    },
    _onClick ($event) {
      if (this.disabled) {
        return
      }
      this._onUserChangedValue($event)
      this.$trigger('change', $event, {
        value: this.sliderValue
      })
    },
    _resetFormData () {
      this.sliderValue = this.min
    },
    _getFormData () {
      const data = {}
      if (this.name !== '') {
        data.value = this.sliderValue
        data.key = this.name
      }
      return data
    }
  }
}
</script>
