// packages/uni-app-plus/src/view/components/map/index.tsx
import { defineBuiltInComponent } from '@dcloudio/uni-components'
import MapDefault from './map'
import MapWeb from './map-web'

const props = {
  id: {
    type: String,
    default: '',
  },
  latitude: {
    type: [Number, String],
    default: '',
  },
  longitude: {
    type: [Number, String],
    default: '',
  },
  scale: {
    type: [String, Number],
    default: 16,
  },
  markers: {
    type: Array,
    default() {
      return []
    },
  },
  polyline: {
    type: Array,
    default() {
      return []
    },
  },
  circles: {
    type: Array,
    default() {
      return []
    },
  },
  polygons: {
    type: Array,
    default() {
      return []
    },
  },
  controls: {
    type: Array,
    default() {
      return []
    },
  },
}

export default /*#__PURE__*/ defineBuiltInComponent({
  name: 'Map',
  props,
  components: {
    MapDefault,
    MapWeb,
  },
  emits: ['click', 'regionchange', 'controltap', 'markertap', 'callouttap'],
  setup(props, { emit }) {
    function onClick(event) {
      emit('click', event)
    }
    function onRegionchange(event) {
      emit('regionchange', event)
    }
    function onControltap(event) {
      emit('controltap', event)
    }
    function onMarkertap(event) {
      emit('markertap', event)
    }
    function onCallouttap(event) {
      emit('callouttap', event)
    }

    return () => {
      if (__uniConfig.qqMapKey) {
        return (
          <MapWeb
            id={props.id}
            latitude={props.latitude}
            longitude={props.longitude}
            scale={props.scale}
            markers={props.markers}
            polyline={props.polyline}
            circles={props.circles}
            polygons={props.polygons}
            controls={props.controls}
            onClick={onClick}
            onRegionchange={onRegionchange}
            onControltap={onControltap}
            onMarkertap={onMarkertap}
            onCallouttap={onCallouttap}
          ></MapWeb>
        )
      } else {
        return (
          <MapDefault
            id={props.id}
            latitude={props.latitude}
            longitude={props.longitude}
            scale={props.scale}
            markers={props.markers}
            polyline={props.polyline}
            circles={props.circles}
            polygons={props.polygons}
            controls={props.controls}
            onClick={onClick}
            onRegionchange={onRegionchange}
            onControltap={onControltap}
            onMarkertap={onMarkertap}
            onCallouttap={onCallouttap}
          ></MapDefault>
        )
      }
    }
  },
})

// packages/uni-h5/src/view/components/map/index.vue
<script lang="ts">
import { Ref, ref, SetupContext, computed } from 'vue'
import { defineBuiltInComponent } from '@dcloudio/uni-components'
import useMap from './use-map'
import props from './use-map/props'

import MapMarker, { Props as MapMarkerProps } from './MapMarker.tsx'
import MapPolyline from './MapPolyline.tsx'
import MapCircle from './MapCircle.tsx'
import MapControl from './MapControl.tsx'
import MapLocation from './MapLocation.tsx'
import MapPolygon from './map-polygon/index.tsx'

import { eventObj } from './map-polygon/event'

export default /*#__PURE__*/ defineBuiltInComponent({
  name: 'Map',
  props,
  emits: [
    'markertap',
    'labeltap',
    'callouttap',
    'controltap',
    'regionchange',
    'tap',
    'click',
    'updated',
    'update:scale',
    'update:latitude',
    'update:longitude',
    // MapPolygon 组件对外暴露的事件
    ...Object.values(eventObj)
  ],
  components: {
    MapMarker,
    MapPolyline,
    MapCircle,
    MapControl,
    MapLocation,
    MapPolygon,
  },
  setup(props, { emit }) {
    const rootRef: Ref<HTMLElement | null> = ref(null)
    const { mapRef, _maps } = useMap(
      props,
      rootRef,
      emit as SetupContext['emit']
    )

    // 剔除未设置 id 属性的 marker
    const validMarkers = computed(() =>
      props.markers.filter((item: MapMarkerProps) => !!item.id)
    )

    return {
      rootRef,
      mapRef,
      validMarkers,
      nativeMapIns: _maps,
    }
  },
})
</script>

<template>
  <uni-map ref="rootRef" :id="id">
    <div
      ref="mapRef"
      style="width: 100%; height: 100%; position: relative; overflow: hidden"
    />
    <MapMarker v-for="item in validMarkers" :key="item.id" v-bind="item" />
    <MapPolyline
      v-for="item in polyline"
      :key="JSON.stringify(item)"
      v-bind="item"
    />
    <MapCircle v-for="item in circles" :key="JSON.stringify(item)" v-bind="item" />
    <MapControl
      v-for="item in controls"
      :key="JSON.stringify(item)"
      v-bind="item"
    />
    <MapLocation v-if="showLocation" />
    <MapPolygon v-for="item in polygons" :key="JSON.stringify(item)" v-bind="item" />
    <div
      style="
        position: absolute;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: hidden;
        pointer-events: none;
      "
    >
      <slot />
    </div>
  </uni-map>
</template>
